### ISSUE TITLE
Building material.js 

### ISSUE THREAD

**Issue by killfill** [taylorSando/om-material-ui#3]
Hi!

How do you build the material.js file?
It seems to contain a specific version of mui and react, i wish to change.

Thanks!!!

**Comment by taylorSando** [comment]
git clone git@github.com:callemall/material-ui.git 

cd material-ui/example/src 

Alter app.jsx to look like: https://gist.github.com/taylorSando/dea6e49a67f71f672f68 

What this is doing is making sure MaterialUI is in the global namespace so you can refer to it in clojurescript. 

You need to run gulp in the examples folder so that it builds the material ui file. 

The new source file will be in the build dir.  You can insert the app.js into the html so that clojurescript can refer to the MaterialUI components.

**Comment by killfill** [comment]
Thanks for the info, closing this in favour of the PR.
